name: terra-draw-route-snap-mode Dry Run Release

permissions:
  contents: write
  id-token: write  # Required for OIDC

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.TERRA_DRAW_ROUTE_SNAP_MODE_PAT }}

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      - name: Update Docs
        run: npm run docs

      - name: Run build
        run: npm run build

      - name: Set git credentials
        run: |
          git config --global user.email "terradraw@githubactions.com"
          git config --global user.name "James Milner"

      - name: Release (Dry Run)
        run: npm run release:dryrun
 